input_lvs = [
    {
        'X': (0, 10.01, 0.01),
        'name': 'Personal qualities',
        'terms': {
            'very low': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'low': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'average': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'high': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },

    {
        'X': (0, 10.01, 0.01),
        'name': 'Knowledge',
        'terms': {
            'little knowledge': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'low knowledge': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'average knowledge': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'high knowledge': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },

    {
        'X': (0, 10.01, 0.01),
        'name': 'Skills',
        'terms': {
            'low skilled': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'average skilled': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'high skilled': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'extremely high skilled': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },

    {
        'X': (0, 20.01, 0.01),
        'name': 'Experience',
        'terms': {
            'no experience': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'small experience': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'medium experience': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'great experience': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    }
]

output_lv = {
    'X': (0, 10.01, 0.01),
    'name': 'Grade',
    'terms': {
        'none to very little': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
        'very low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
        'low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
        'medium': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
        'above medium': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
        'high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
        'extremely high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
    }
}

rule_base = [
    (('very low', 'little knowledge', 'low skilled', 'no experience'), 'none to very little'),
    (('very low', 'little knowledge', 'low skilled', 'small experience'), 'none to very little'),
    (('very low', 'little knowledge', 'low skilled', 'medium experience'), 'none to very little'),
    (('very low', 'little knowledge', 'low skilled', 'great experience'), 'none to very little'),
    (('very low', 'little knowledge', 'average skilled', 'no experience'), 'very low'),
    (('very low', 'little knowledge', 'average skilled', 'small experience'), 'very low'),
    (('very low', 'little knowledge', 'average skilled', 'medium experience'), 'very low'),
    (('very low', 'little knowledge', 'average skilled', 'great experience'), 'very low'),
    (('very low', 'little knowledge', 'high skilled', 'no experience'), 'low'),
    (('very low', 'little knowledge', 'high skilled', 'small experience'), 'low'),
    (('very low', 'little knowledge', 'high skilled', 'medium experience'), 'medium'),
    (('very low', 'little knowledge', 'high skilled', 'great experience'), 'medium'),
    (('very low', 'little knowledge', 'extremely high skilled', 'no experience'), 'medium'),
    (('very low', 'little knowledge', 'extremely high skilled', 'small experience'), 'medium'),
    (('very low', 'little knowledge', 'extremely high skilled', 'medium experience'), 'medium'),
    (('very low', 'little knowledge', 'extremely high skilled', 'great experience'), 'medium'),
    (('very low', 'low knowledge', 'low skilled', 'no experience'), 'very low'),
    (('very low', 'low knowledge', 'low skilled', 'small experience'), 'very low'),
    (('very low', 'low knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('very low', 'low knowledge', 'low skilled', 'great experience'), 'very low'),
    (('very low', 'low knowledge', 'average skilled', 'no experience'), 'low'),
    (('very low', 'low knowledge', 'average skilled', 'small experience'), 'low'),
    (('very low', 'low knowledge', 'average skilled', 'medium experience'), 'low'),
    (('very low', 'low knowledge', 'average skilled', 'great experience'), 'low'),
    (('very low', 'low knowledge', 'high skilled', 'no experience'), 'medium'),
    (('very low', 'low knowledge', 'high skilled', 'small experience'), 'medium'),
    (('very low', 'low knowledge', 'high skilled', 'medium experience'), 'medium'),
    (('very low', 'low knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('very low', 'low knowledge', 'extremely high skilled', 'no experience'), 'above medium'),
    (('very low', 'low knowledge', 'extremely high skilled', 'small experience'), 'above medium'),
    (('very low', 'low knowledge', 'extremely high skilled', 'medium experience'), 'above medium'),
    (('very low', 'low knowledge', 'extremely high skilled', 'great experience'), 'above medium'),
    (('very low', 'average knowledge', 'low skilled', 'no experience'), 'very low'),
    (('very low', 'average knowledge', 'low skilled', 'small experience'), 'very low'),
    (('very low', 'average knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('very low', 'average knowledge', 'low skilled', 'great experience'), 'very low'),
    (('very low', 'average knowledge', 'average skilled', 'no experience'), 'low'),
    (('very low', 'average knowledge', 'average skilled', 'small experience'), 'low'),
    (('very low', 'average knowledge', 'average skilled', 'medium experience'), 'low'),
    (('very low', 'average knowledge', 'average skilled', 'great experience'), 'low'),
    (('very low', 'average knowledge', 'high skilled', 'no experience'), 'medium'),
    (('very low', 'average knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('very low', 'average knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('very low', 'average knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('very low', 'average knowledge', 'extremely high skilled', 'no experience'), 'above medium'),
    (('very low', 'average knowledge', 'extremely high skilled', 'small experience'), 'above medium'),
    (('very low', 'average knowledge', 'extremely high skilled', 'medium experience'), 'above medium'),
    (('very low', 'average knowledge', 'extremely high skilled', 'great experience'), 'above medium'),
    (('very low', 'high knowledge', 'low skilled', 'no experience'), 'low'),
    (('very low', 'high knowledge', 'low skilled', 'small experience'), 'low'),
    (('very low', 'high knowledge', 'low skilled', 'medium experience'), 'low'),
    (('very low', 'high knowledge', 'low skilled', 'great experience'), 'low'),
    (('very low', 'high knowledge', 'average skilled', 'no experience'), 'medium'),
    (('very low', 'high knowledge', 'average skilled', 'small experience'), 'medium'),
    (('very low', 'high knowledge', 'average skilled', 'medium experience'), 'medium'),
    (('very low', 'high knowledge', 'average skilled', 'great experience'), 'medium'),
    (('very low', 'high knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('very low', 'high knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('very low', 'high knowledge', 'high skilled', 'medium experience'), 'high'),
    (('very low', 'high knowledge', 'high skilled', 'great experience'), 'high'),
    (('very low', 'high knowledge', 'extremely high skilled', 'no experience'), 'high'),
    (('very low', 'high knowledge', 'extremely high skilled', 'small experience'), 'high'),
    (('very low', 'high knowledge', 'extremely high skilled', 'medium experience'), 'high'),
    (('very low', 'high knowledge', 'extremely high skilled', 'great experience'), 'high'),
    (('low', 'little knowledge', 'low skilled', 'no experience'), 'none to very little'),
    (('low', 'little knowledge', 'low skilled', 'small experience'), 'none to very little'),
    (('low', 'little knowledge', 'low skilled', 'medium experience'), 'none to very little'),
    (('low', 'little knowledge', 'low skilled', 'great experience'), 'none to very little'),
    (('low', 'little knowledge', 'average skilled', 'no experience'), 'very low'),
    (('low', 'little knowledge', 'average skilled', 'small experience'), 'very low'),
    (('low', 'little knowledge', 'average skilled', 'medium experience'), 'very low'),
    (('low', 'little knowledge', 'average skilled', 'great experience'), 'very low'),
    (('low', 'little knowledge', 'high skilled', 'no experience'), 'low'),
    (('low', 'little knowledge', 'high skilled', 'small experience'), 'medium'),
    (('low', 'little knowledge', 'high skilled', 'medium experience'), 'medium'),
    (('low', 'little knowledge', 'high skilled', 'great experience'), 'medium'),
    (('low', 'little knowledge', 'extremely high skilled', 'no experience'), 'medium'),
    (('low', 'little knowledge', 'extremely high skilled', 'small experience'), 'medium'),
    (('low', 'little knowledge', 'extremely high skilled', 'medium experience'), 'medium'),
    (('low', 'little knowledge', 'extremely high skilled', 'great experience'), 'medium'),
    (('low', 'low knowledge', 'low skilled', 'no experience'), 'very low'),
    (('low', 'low knowledge', 'low skilled', 'small experience'), 'very low'),
    (('low', 'low knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('low', 'low knowledge', 'low skilled', 'great experience'), 'very low'),
    (('low', 'low knowledge', 'average skilled', 'no experience'), 'low'),
    (('low', 'low knowledge', 'average skilled', 'small experience'), 'low'),
    (('low', 'low knowledge', 'average skilled', 'medium experience'), 'low'),
    (('low', 'low knowledge', 'average skilled', 'great experience'), 'low'),
    (('low', 'low knowledge', 'high skilled', 'no experience'), 'medium'),
    (('low', 'low knowledge', 'high skilled', 'small experience'), 'medium'),
    (('low', 'low knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('low', 'low knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('low', 'low knowledge', 'extremely high skilled', 'no experience'), 'above medium'),
    (('low', 'low knowledge', 'extremely high skilled', 'small experience'), 'above medium'),
    (('low', 'low knowledge', 'extremely high skilled', 'medium experience'), 'above medium'),
    (('low', 'low knowledge', 'extremely high skilled', 'great experience'), 'above medium'),
    (('low', 'average knowledge', 'low skilled', 'no experience'), 'very low'),
    (('low', 'average knowledge', 'low skilled', 'small experience'), 'very low'),
    (('low', 'average knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('low', 'average knowledge', 'low skilled', 'great experience'), 'low'),
    (('low', 'average knowledge', 'average skilled', 'no experience'), 'low'),
    (('low', 'average knowledge', 'average skilled', 'small experience'), 'low'),
    (('low', 'average knowledge', 'average skilled', 'medium experience'), 'low'),
    (('low', 'average knowledge', 'average skilled', 'great experience'), 'medium'),
    (('low', 'average knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('low', 'average knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('low', 'average knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('low', 'average knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('low', 'average knowledge', 'extremely high skilled', 'no experience'), 'above medium'),
    (('low', 'average knowledge', 'extremely high skilled', 'small experience'), 'above medium'),
    (('low', 'average knowledge', 'extremely high skilled', 'medium experience'), 'above medium'),
    (('low', 'average knowledge', 'extremely high skilled', 'great experience'), 'high'),
    (('low', 'high knowledge', 'low skilled', 'no experience'), 'low'),
    (('low', 'high knowledge', 'low skilled', 'small experience'), 'low'),
    (('low', 'high knowledge', 'low skilled', 'medium experience'), 'low'),
    (('low', 'high knowledge', 'low skilled', 'great experience'), 'low'),
    (('low', 'high knowledge', 'average skilled', 'no experience'), 'medium'),
    (('low', 'high knowledge', 'average skilled', 'small experience'), 'medium'),
    (('low', 'high knowledge', 'average skilled', 'medium experience'), 'medium'),
    (('low', 'high knowledge', 'average skilled', 'great experience'), 'medium'),
    (('low', 'high knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('low', 'high knowledge', 'high skilled', 'small experience'), 'high'),
    (('low', 'high knowledge', 'high skilled', 'medium experience'), 'high'),
    (('low', 'high knowledge', 'high skilled', 'great experience'), 'high'),
    (('low', 'high knowledge', 'extremely high skilled', 'no experience'), 'high'),
    (('low', 'high knowledge', 'extremely high skilled', 'small experience'), 'high'),
    (('low', 'high knowledge', 'extremely high skilled', 'medium experience'), 'high'),
    (('low', 'high knowledge', 'extremely high skilled', 'great experience'), 'high'),
    (('average', 'little knowledge', 'low skilled', 'no experience'), 'none to very little'),
    (('average', 'little knowledge', 'low skilled', 'small experience'), 'none to very little'),
    (('average', 'little knowledge', 'low skilled', 'medium experience'), 'none to very little'),
    (('average', 'little knowledge', 'low skilled', 'great experience'), 'very low'),
    (('average', 'little knowledge', 'average skilled', 'no experience'), 'very low'),
    (('average', 'little knowledge', 'average skilled', 'small experience'), 'very low'),
    (('average', 'little knowledge', 'average skilled', 'medium experience'), 'very low'),
    (('average', 'little knowledge', 'average skilled', 'great experience'), 'low'),
    (('average', 'little knowledge', 'high skilled', 'no experience'), 'medium'),
    (('average', 'little knowledge', 'high skilled', 'small experience'), 'medium'),
    (('average', 'little knowledge', 'high skilled', 'medium experience'), 'medium'),
    (('average', 'little knowledge', 'high skilled', 'great experience'), 'medium'),
    (('average', 'little knowledge', 'extremely high skilled', 'no experience'), 'medium'),
    (('average', 'little knowledge', 'extremely high skilled', 'small experience'), 'medium'),
    (('average', 'little knowledge', 'extremely high skilled', 'medium experience'), 'medium'),
    (('average', 'little knowledge', 'extremely high skilled', 'great experience'), 'above medium'),
    (('average', 'low knowledge', 'low skilled', 'no experience'), 'very low'),
    (('average', 'low knowledge', 'low skilled', 'small experience'), 'very low'),
    (('average', 'low knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('average', 'low knowledge', 'low skilled', 'great experience'), 'very low'),
    (('average', 'low knowledge', 'average skilled', 'no experience'), 'low'),
    (('average', 'low knowledge', 'average skilled', 'small experience'), 'low'),
    (('average', 'low knowledge', 'average skilled', 'medium experience'), 'low'),
    (('average', 'low knowledge', 'average skilled', 'great experience'), 'low'),
    (('average', 'low knowledge', 'high skilled', 'no experience'), 'medium'),
    (('average', 'low knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('average', 'low knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('average', 'low knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('average', 'low knowledge', 'extremely high skilled', 'no experience'), 'above medium'),
    (('average', 'low knowledge', 'extremely high skilled', 'small experience'), 'above medium'),
    (('average', 'low knowledge', 'extremely high skilled', 'medium experience'), 'above medium'),
    (('average', 'low knowledge', 'extremely high skilled', 'great experience'), 'above medium'),
    (('average', 'average knowledge', 'low skilled', 'no experience'), 'very low'),
    (('average', 'average knowledge', 'low skilled', 'small experience'), 'very low'),
    (('average', 'average knowledge', 'low skilled', 'medium experience'), 'low'),
    (('average', 'average knowledge', 'low skilled', 'great experience'), 'low'),
    (('average', 'average knowledge', 'average skilled', 'no experience'), 'low'),
    (('average', 'average knowledge', 'average skilled', 'small experience'), 'low'),
    (('average', 'average knowledge', 'average skilled', 'medium experience'), 'medium'),
    (('average', 'average knowledge', 'average skilled', 'great experience'), 'medium'),
    (('average', 'average knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('average', 'average knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('average', 'average knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('average', 'average knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('average', 'average knowledge', 'extremely high skilled', 'no experience'), 'above medium'),
    (('average', 'average knowledge', 'extremely high skilled', 'small experience'), 'above medium'),
    (('average', 'average knowledge', 'extremely high skilled', 'medium experience'), 'high'),
    (('average', 'average knowledge', 'extremely high skilled', 'great experience'), 'high'),
    (('average', 'high knowledge', 'low skilled', 'no experience'), 'low'),
    (('average', 'high knowledge', 'low skilled', 'small experience'), 'low'),
    (('average', 'high knowledge', 'low skilled', 'medium experience'), 'low'),
    (('average', 'high knowledge', 'low skilled', 'great experience'), 'medium'),
    (('average', 'high knowledge', 'average skilled', 'no experience'), 'medium'),
    (('average', 'high knowledge', 'average skilled', 'small experience'), 'medium'),
    (('average', 'high knowledge', 'average skilled', 'medium experience'), 'medium'),
    (('average', 'high knowledge', 'average skilled', 'great experience'), 'above medium'),
    (('average', 'high knowledge', 'high skilled', 'no experience'), 'high'),
    (('average', 'high knowledge', 'high skilled', 'small experience'), 'high'),
    (('average', 'high knowledge', 'high skilled', 'medium experience'), 'high'),
    (('average', 'high knowledge', 'high skilled', 'great experience'), 'high'),
    (('average', 'high knowledge', 'extremely high skilled', 'no experience'), 'high'),
    (('average', 'high knowledge', 'extremely high skilled', 'small experience'), 'high'),
    (('average', 'high knowledge', 'extremely high skilled', 'medium experience'), 'high'),
    (('average', 'high knowledge', 'extremely high skilled', 'great experience'), 'extremely high'),
    (('high', 'little knowledge', 'low skilled', 'no experience'), 'none to very little'),
    (('high', 'little knowledge', 'low skilled', 'small experience'), 'none to very little'),
    (('high', 'little knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('high', 'little knowledge', 'low skilled', 'great experience'), 'very low'),
    (('high', 'little knowledge', 'average skilled', 'no experience'), 'very low'),
    (('high', 'little knowledge', 'average skilled', 'small experience'), 'very low'),
    (('high', 'little knowledge', 'average skilled', 'medium experience'), 'low'),
    (('high', 'little knowledge', 'average skilled', 'great experience'), 'low'),
    (('high', 'little knowledge', 'high skilled', 'no experience'), 'medium'),
    (('high', 'little knowledge', 'high skilled', 'small experience'), 'medium'),
    (('high', 'little knowledge', 'high skilled', 'medium experience'), 'medium'),
    (('high', 'little knowledge', 'high skilled', 'great experience'), 'medium'),
    (('high', 'little knowledge', 'extremely high skilled', 'no experience'), 'medium'),
    (('high', 'little knowledge', 'extremely high skilled', 'small experience'), 'medium'),
    (('high', 'little knowledge', 'extremely high skilled', 'medium experience'), 'above medium'),
    (('high', 'little knowledge', 'extremely high skilled', 'great experience'), 'above medium'),
    (('high', 'low knowledge', 'low skilled', 'no experience'), 'very low'),
    (('high', 'low knowledge', 'low skilled', 'small experience'), 'very low'),
    (('high', 'low knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('high', 'low knowledge', 'low skilled', 'great experience'), 'low'),
    (('high', 'low knowledge', 'average skilled', 'no experience'), 'low'),
    (('high', 'low knowledge', 'average skilled', 'small experience'), 'low'),
    (('high', 'low knowledge', 'average skilled', 'medium experience'), 'low'),
    (('high', 'low knowledge', 'average skilled', 'great experience'), 'medium'),
    (('high', 'low knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('high', 'low knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('high', 'low knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('high', 'low knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('high', 'low knowledge', 'extremely high skilled', 'no experience'), 'above medium'),
    (('high', 'low knowledge', 'extremely high skilled', 'small experience'), 'above medium'),
    (('high', 'low knowledge', 'extremely high skilled', 'medium experience'), 'above medium'),
    (('high', 'low knowledge', 'extremely high skilled', 'great experience'), 'high'),
    (('high', 'average knowledge', 'low skilled', 'no experience'), 'low'),
    (('high', 'average knowledge', 'low skilled', 'small experience'), 'low'),
    (('high', 'average knowledge', 'low skilled', 'medium experience'), 'low'),
    (('high', 'average knowledge', 'low skilled', 'great experience'), 'low'),
    (('high', 'average knowledge', 'average skilled', 'no experience'), 'medium'),
    (('high', 'average knowledge', 'average skilled', 'small experience'), 'medium'),
    (('high', 'average knowledge', 'average skilled', 'medium experience'), 'medium'),
    (('high', 'average knowledge', 'average skilled', 'great experience'), 'medium'),
    (('high', 'average knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('high', 'average knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('high', 'average knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('high', 'average knowledge', 'high skilled', 'great experience'), 'high'),
    (('high', 'average knowledge', 'extremely high skilled', 'no experience'), 'high'),
    (('high', 'average knowledge', 'extremely high skilled', 'small experience'), 'high'),
    (('high', 'average knowledge', 'extremely high skilled', 'medium experience'), 'high'),
    (('high', 'average knowledge', 'extremely high skilled', 'great experience'), 'high'),
    (('high', 'high knowledge', 'low skilled', 'no experience'), 'low'),
    (('high', 'high knowledge', 'low skilled', 'small experience'), 'low'),
    (('high', 'high knowledge', 'low skilled', 'medium experience'), 'medium'),
    (('high', 'high knowledge', 'low skilled', 'great experience'), 'medium'),
    (('high', 'high knowledge', 'average skilled', 'no experience'), 'medium'),
    (('high', 'high knowledge', 'average skilled', 'small experience'), 'medium'),
    (('high', 'high knowledge', 'average skilled', 'medium experience'), 'above medium'),
    (('high', 'high knowledge', 'average skilled', 'great experience'), 'above medium'),
    (('high', 'high knowledge', 'high skilled', 'no experience'), 'high'),
    (('high', 'high knowledge', 'high skilled', 'small experience'), 'high'),
    (('high', 'high knowledge', 'high skilled', 'medium experience'), 'high'),
    (('high', 'high knowledge', 'high skilled', 'great experience'), 'high'),
    (('high', 'high knowledge', 'extremely high skilled', 'no experience'), 'high'),
    (('high', 'high knowledge', 'extremely high skilled', 'small experience'), 'high'),
    (('high', 'high knowledge', 'extremely high skilled', 'medium experience'), 'extremely high'),
    (('high', 'high knowledge', 'extremely high skilled', 'great experience'), 'extremely high'),
]
